[package]
name = "compose-animation"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Animation system for Compose-RS"

[dependencies]
compose-core = { path = "../compose-core" }

[features]
default = []
